#!/usr/bin/env python
# 从 `try_except.py` 中复制而来
def my_calculator(x):
    return x-1
